parameters:
#    crevax_site.example.class: Crevax\SiteBundle\Example

services:
#    crevax_site.example:
#        class: %crevax_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
