crevax_library:
    resource: "@CrevaxLibraryBundle/Resources/config/routing.yml"
    prefix:   /library

crevax_portfolio:
    resource: "@CrevaxPortfolioBundle/Resources/config/routing.yml"
    prefix:   /portfolio

crevax_dossier:
    resource: "@CrevaxDossierBundle/Resources/config/routing.yml"
    prefix:   /profile

crevax_site:
    resource: "@CrevaxSiteBundle/Resources/config/routing.yml"
    prefix:   /

crevax_user:
    resource: "@CrevaxUserBundle/Resources/config/routing.yml"
    prefix:   /user