parameters:
#    crevax_dossier.example.class: Crevax\DossierBundle\Example

services:
#    crevax_dossier.example:
#        class: %crevax_dossier.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
