crevax_library_homepage:
  pattern:  /
  methods: GET
  defaults: { _controller: CrevaxLibraryBundle:Library:index }

crevax_library_author_index:
  pattern:  /authors
  methods: GET
  defaults: { _controller: CrevaxLibraryBundle:Author:index }

crevax_library_author_new:
  pattern:  /authors/new
  methods: [GET, POST]
  defaults: { _controller: CrevaxLibraryBundle:Author:new }

crevax_library_book_index:
  pattern:  /books
  methods: GET
  defaults: { _controller: CrevaxLibraryBundle:Book:index }

crevax_library_book_new:
  pattern:  /books/new
  methods: [GET, POST]
  defaults: { _controller: CrevaxLibraryBundle:Book:new }