crevax_library_homepage:
  pattern:  /
  defaults: { _controller: CrevaxLibraryBundle:Library:index }

crevax_library_author_index:
  pattern:  /authors
  defaults: { _controller: CrevaxLibraryBundle:Author:index }

crevax_library_author_new:
  pattern:  /authors/new
  defaults: { _controller: CrevaxLibraryBundle:Author:new }