parameters:
#    crevax_user.example.class: Crevax\UserBundle\Example

services:
#    crevax_user.example:
#        class: %crevax_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
